name: Release

on:
  release:
    types: [published]

jobs:
  PyPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip build wheel twine
      - name: Build dist packages
        run: python -m build --sdist --wheel
      - name: Upload packages
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
